### ISSUE TITLE
Dupe fix

### ISSUE THREAD

**Issue by muriplz** [skippyall/CreateFabricFixes#2]
Thanks a lot for bringing this mod as a workaround for crashes!

I'm trying to fix a dupe bug https://github.com/Creators-of-Create/Create/issues/4880
that also happens on the fabric fork

I haven't been able to figure out what class/code is at wrong here, must be a hard issue since its open since may 2023,
it would be cool to have this fix too!

you can contact me on discord (muriplz),
I undertand anyways that this is out of scope of this mod since it is not a crash and a very specific dupe

**Comment by skippyall** [comment]
I think that I will include this. Thank you pointing it out.

**Comment by skippyall** [comment]
I found the bug in https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/content/contraptions/behaviour/dispenser/DropperMovementBehaviour.java in line 47 and following. Each stack is increased by the number of items that were extracted with ItemStack#sameItem method as a filter, which doesn't check for nbt data.

**Comment by skippyall** [comment]
They'd better use ItemStack#matches

**Comment by skippyall** [comment]
No they'd better use ItemStack#isSameItemSameTags because it should work with different counts

**Comment by muriplz** [comment]
https://pastes.io/rch9rjbdxv
I tested this on a prod server and got this crash! 
I'm not sure as if this stacktrace is due to an issue with it or some other unrelated crash happened and made it throw an stacktrace.
It's cut because I could only see it in console with it happened, wasn't pasted to any log file or crash file

**Comment by skippyall** [comment]
This is caused by this mod, however, the important part about what exactly caused the crash is missing, so I cannot fix this without more information.

**Comment by skippyall** [comment]
When did it crash? On startup or while playing?

**Comment by muriplz** [comment]
I'll try to replicate it to get the full log, its during the game, not startup

**Comment by muriplz** [comment]
ava.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.logistics.filter.ItemAttribute.serializeNBT(net.minecraft.class_2487)" because the return value of "com.simibubi.create.foundation.utility.Pair.getFirst()" is null
	at com.simibubi.create.content.logistics.filter.AttributeFilterMenu.lambda$saveData$1(AttributeFilterMenu.java:152)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.simibubi.create.content.logistics.filter.AttributeFilterMenu.saveData(AttributeFilterMenu.java:147)
	at com.simibubi.create.content.logistics.filter.AttributeFilterMenu.saveData(AttributeFilterMenu.java:25)
	at com.simibubi.create.foundation.gui.menu.MenuBase.method_7595(MenuBase.java:59)
	at net.minecraft.class_3222.method_14247(class_3222.java:1089)
	at net.minecraft.class_1657.method_5650(class_1657.java:1412)
	at net.minecraft.class_3218.method_18770(class_3218.java:929)
	at net.minecraft.class_3324.method_14611(class_3324.java:413)
	at net.minecraft.class_3244.method_10839(class_3244.java:1228)
	at net.minecraft.class_2535.method_10768(class_2535.java:452)
	at net.minecraft.class_3242.method_14357(class_3242.java:185)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by skippyall** [comment]
That's a separate issue

**Comment by muriplz** [comment]
My bad, it seems to work fine, the items are not longer duped, although:
- Droppers on contraption now dont work, although they dont vanish items
- When trying to dupe, it does vanish the toolbox 
![image](https://github.com/skippyall/CreateFabricFixes/assets/46825658/89425cbb-15bd-48f5-8b54-a241d73f0191)
This array has the empty toolbox in the dropper and the toolbox with stuff inside in the barrel

No logs on console or anything

Sorry for the late response here

**Comment by skippyall** [comment]
It is intended that it doesn't do anything if there is no item with exact same data in the barrel and just one item in the dropper.
