### ISSUE TITLE
compatability with create sodium fabric fix

### ISSUE THREAD

**Issue by Lumenyl-Cal** [skippyall/CreateFabricFixes#3]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Create Fabric Fixes' (createfabricfixes) 0.0.1+1.20.1 (C:\Users\meaf\AppData\Roaming\com.modrinth.theseus\profiles\TE\mods\createfabricfixes-0.0.3+1.20.1-create-0.5.1d.jar).
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by skippyall** [comment]
Already fixed, please use the latest version
